### ISSUE TITLE
Esoteric blade doesn't work with gloves of dueling?

### ISSUE THREAD

**Issue by deng-tianhan** [NosVladimir/KineticArchetypes#7] opened 2023-07-22 09:45 UTC
Not sure if this is replicable... esoteric blade 5 wearing lesser gloves or dueling:

- In the character sheet +1 AB from weapon training is shown, but not the +1 damage
- In the combat log both +1 AB and +1 damage are shown

TBH esoteric blade is doing so much damage, gloves of dueling not really needed. 🤣 I'm just wondering if this is an oversight from your awesome mod.

**Comment by NosVladimir** [comment] 2023-07-22 09:49
The damage calculation of kinetic blades in the character sheet is always wrong, it doesn't take into account a lot of things even from the base game, including e.g. power attack, overflow and my custom weapon training. As long as the combat log displays correctly it's not a big issue.

Esoteric blade 5 with lesser gloves of dueling should get +2 AB and damage from weapon training (1 base + 1 golves). Did you mean you only get +1 with wearing the golves? Then that might be a real issue

**Comment by deng-tianhan** [comment] 2023-07-22 09:53
> Did you mean you only get +1 with wearing the golves?

Yes. Only +1 for both AB and damage

**Comment by NosVladimir** [comment] 2023-07-22 10:00
I quickly tested and from my side the golves are correctly applying the bonus AB and damage. I suspect it's another mod that changed how these golves work, or probably how weapon training work?

**Comment by deng-tianhan** [comment] 2023-07-22 10:04
Hmmm... fair. Cross-mod bug will be much harder to pinpoint the root cause then.

**Comment by NosVladimir** [comment] 2023-07-22 10:09
Could you provide a list of your mods? Then maybe I can try to figure out which one was causing this

**Comment by deng-tianhan** [comment] 2023-07-22 10:09
>[141.5773 - TestSwarm]: Resource loaded: GlovesOfDuelingFeature, BlueprintFeature, 5238b7d5f4c81574ba914d609ac1e692
[141.5773 - TestSwarm]: Resource loaded: GlovesOfDuelingFeature2, BlueprintFeature, f063942ce72136c49a12d34a3fd88197
[141.5773 - TestSwarm]: Resource loaded: GlovesOfTheScribeFeature, BlueprintFeature, 82ec84da788ab854eb44e594b2ecf792

Suspecting these lines. From ninja class https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/233

**Comment by deng-tianhan** [comment] 2023-07-22 10:10
list of mods from player log:

>[Manager] Parsing mods.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\0ToyBox0\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\AddedFeats\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\AlternateHumanTraits\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\BubbleTweaks\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\CharacterOptionsPlus\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\CustomNpcPortraits\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\DarkCodex\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\ExpandedContent\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\IsekaiMod\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\KineticArchetypes\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\KineticistElementsExpanded\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\LevelableAivu\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MartialExcellence\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MicroscopicContentExpansion\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MiscTweaksAndFixes\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\ModMenu\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MoreCantrips\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MorvarchsPlaystyleExpansions\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MultipleArchetypes\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MysticalMayhem\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MythicArcanist\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\MythicSpellbookTweaks\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\PFWOTR_CLUNLOCKER\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\PhoenixsCantrips\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\Psionics\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\QuickCast\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\ResourceUnification\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\RespecWrath\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\SamuraiMod\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\SpellbookMerge\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\Swashbuckler\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\TabletopTweaks-Base\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\TabletopTweaks-Core\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\TabletopTweaks-Reworks\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\TurnbasedCombatDelay\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\VisualAdjustments2\Info.json'.
[Manager] Reading file 'D:\Games\Pathfinder Wrath of the Righteous\Mods\WeaponFocusPlus\Info.json'.
[Manager] Sorting mods.

**Comment by NosVladimir** [comment] 2023-07-22 10:31
TestSwarm is indeed the log channel used by Ninja, it might be the cause. 

Another possibility is Samurai, which also adds a custom Samurai Weapon Training, but from looking at its code I don't see places where it modifies how the gloves behave.

It might also be WeaponFocusPlus, which also does some things with fighter weapon groups, but I also don't see how that could affect the gloves.

Anyway, the bonuses from the golves are almost negligible. If you feel like it's not very important to your playthrough you may close the issue, otherwise we can also leave the issue open to notify people about this bug

**Closed** 2023-07-22 16:08 UTC
Labels: cross-mod bug, unable to fix
